#+STARTUP: overview hideblocks indent inlineimages
#+PROPERTY: header-args:R :exports both :results output :session *R*
* README

- Practice for ~plot~ customization as discussed in the lecture
- Includes example of downloading CSV data into a data frame
- Create R code blocks to complete this file
- Submit Org-file on Canvas when you're done
* TODO Getting the data

Save data *from the web* to an R data frame ~df~:
#+begin_src R
  df <- read.csv(
    file="https://raw.githubusercontent.com/birkenkrahe/dviz/piHome/data/dataset.csv",
    header=TRUE)
  str(df)
#+end_src

* TODO Plotting the data

1) For the R code blocks with graphics output, you need these header
   arguments in this format exactly when writing to a file ~plot.png~ in
   the current directory:

   ~:results graphics file :file plot.png~

2) Save the ~Weight~ vector as ~x~ and the ~Height~ vector as ~y~ for later.

   #+begin_src R
     x <- df$Weight
     x
     y <- df$Height
     y
   #+end_src

3) Create a scatterplot of the weight on the ~x~ axis and the height on
   the ~y~ axis. Save the plot as ~scatter.png~.

   #+begin_src R :results graphics file :file scatter.png
     plot(y ~ x)
   #+end_src

* TODO Customize the plot

1) Customize the plot by using different point characters to identify
   all people, who are equal to or taller than 180 cm, and save the
   resulting plot as ~pch.png~.

   - Define an appropriate ~index~ vector using the ~which~ function
   - Call ~plot~ as before but don't draw any points
   - Call ~points[index]~ for outliers ,and ~points[-index]~ for others
   - Inside the ~points~ function calls, use ~pch=18~ and ~cex=1~ for the
     outliers, and ~pch=6~, ~cex=1.3~ for the other points

   #+begin_src R :results graphics file :file pch.png
     plot(y ~ x, type="n")
     index <- which(y > 180)
     points(x[index], y[index], pch=18, cex=2)
     points(x[-index], y[-index], pch=6, cex=1.3)
   #+end_src

2) Label the axes and give the plot a suitable title. Save your final
   plot in ~final.png~.

   #+begin_src R :results graphics file :file final.png
     plot(y ~ x, type="n",
          main="Weight vs. Height of 10 people",
          ylab="Weight", xlab="Height")
     index <- which(y > 180)
     points(x[index], y[index], pch=18, cex=2)
     points(x[-index], y[-index], pch=6, cex=1.3)
   #+end_src

* TODO Add a trendline

In the last plot, we indexed all male participants taller than or
equal than 180 cm (about 6'). Now we want to 1) add a trendline, 2)
add a suitable legend.

1) To add a trendline, define a model using the ~lm~ function on the two
   coordinate vectors ~y~ and ~x~, and store it in ~trend~

   #+begin_src R
     ...
   #+end_src

2) Use the model's intercept and slope values to draw a red, dashed,
   thick trend line. Store the resulting graph in ~trend.png~.

   You need to recreated the calls to ~plot~ and ~points~ for this
   graph. Draw this graph first, then add the trendline.

* TODO Add text for outliers

Add the text "Outlier" to the three outlying points of the plot. You
can use the following label: ~paste("Outlier -->")~. Left-align the
text and make sure that the text does not obscure the data.

Use the previous code block and store the graph in ~text.png~.

* TODO Add a legend

Add a legend for the trendline and for the two plot point types. Store
the plot in the file ~people.png~.

 
